/**
 * BackendSetup — shows copy-pasteable setup instructions when the backend is offline.
 * Not rendered in production; kept here as reference for the developer.
 * 
 * ─────────────────────────────────────────────────────────────────────────────
 * MACROPULSE FASTAPI BACKEND — COMPLETE SOURCE
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * FOLDER STRUCTURE
 * ────────────────
 * macropulse_backend/
 * ├── main.py
 * ├── config.py
 * ├── requirements.txt
 * ├── .env.example
 * ├── generate_demo_data.py
 * ├── api/
 * │   ├── __init__.py
 * │   └── routes.py
 * ├── core/
 * │   ├── __init__.py
 * │   ├── features.py
 * │   ├── regime.py
 * │   └── explanation.py
 * ├── models/
 * │   ├── __init__.py
 * │   └── schemas.py
 * ├── services/
 * │   ├── __init__.py
 * │   ├── data_source.py
 * │   └── state.py
 * ├── data/
 * │   └── demo_prices.csv   ← generated by generate_demo_data.py
 * └── tests/
 *     ├── __init__.py
 *     ├── test_features.py
 *     └── test_regime.py
 *
 * QUICK START
 * ───────────
 * cd macropulse_backend
 * python -m venv venv && source venv/bin/activate
 * pip install -r requirements.txt
 * python generate_demo_data.py        # creates data/demo_prices.csv
 * cp .env.example .env
 * uvicorn main:app --reload           # http://localhost:8000
 *
 * In the React app root add:
 * VITE_API_URL=http://localhost:8000  to .env.local
 */

export default null; // not a React component — documentation only